var = input('Enter with something: ')
print('Is that numeric?', var.isnumeric())
print('Is that alphabetic?', var.isalpha())
print('Is that alphanumeric?', var.isalnum())
print('Is that a digit?', var.isdigit())
print('Is that in lowercase?', var.islower())
print('Is that in uppercase?', var.isupper())
print('Is that a title?', var.istitle())
print('Is that a decimal?', var.isdecimal())
