n1 = int(input('Entre com um número: '))
tabuada = 'TABUADA'
print('{:~^35}'.format(tabuada))
print('{}\tx\t{}\t=\t{}'.format(n1,1,n1*1))
print('{}\tx\t{}\t=\t{}'.format(n1,2,n1*2))
print('{}\tx\t{}\t=\t{}'.format(n1,3,n1*3))
print('{}\tx\t{}\t=\t{}'.format(n1,4,n1*4))
print('{}\tx\t{}\t=\t{}'.format(n1,5,n1*5))
print('{}\tx\t{}\t=\t{}'.format(n1,6,n1*6))
print('{}\tx\t{}\t=\t{}'.format(n1,7,n1*7))
print('{}\tx\t{}\t=\t{}'.format(n1,8,n1*8))
print('{}\tx\t{}\t=\t{}'.format(n1,9,n1*9))
print('{}\tx\t{}\t=\t{}'.format(n1,10,n1*10))
print('~'*35) 