print('SUM CALCULATOR')
n1 = int(input('Enter with the first number: ')) 
n2 = int(input('Enter with the second number: ')) 
sum = int(n1+n2)
print('The sum result of {} plus {} is {}'.format(n1,n2,sum))